version: "3.8"
networks:
  appli:
services:
  db:
    container_name: bdd
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_PASSWORD: root
    ports:
      - "4306:3306"
    volumes:
      - ./docker/db:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    restart: always # always restart unless stopped manually
    networks:
      - appli
  php:
    environment:
      PHP_IDE_CONFIG: "serverName=docker"
    container_name: php
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    volumes:
      - .:/var/www/html
      - ./docker/php/conf.d:/usr/local/etc/php/conf.d
    ports:
      - "9000:9000" # PHP-FPM port
    networks:
      - appli
    depends_on:
      - db

  nginx:
    container_name: nginx
    image: nginx:latest
    volumes:
      - .:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8080:80"
    networks:
      - appli
    depends_on:
      - php

